# 应用错误捕捉

## react Error Boundaries

- [错误边界（Error Boundaries）](https://react.docschina.org/docs/error-boundaries.html)

```js
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props)
    this.state = { hasError: false }
  }

  static getDerivedStateFromError(error) {
    // 更新 state 使下一次渲染能够显示降级后的 UI
    return { hasError: true }
  }

  componentDidCatch(error, errorInfo) {
    // 你同样可以将错误日志上报给服务器
    logErrorToMyService(error, errorInfo)
  }

  render() {
    if (this.state.hasError) {
      // 你可以自定义降级后的 UI 并渲染
      return <h1>Something went wrong.</h1>
    }

    return this.props.children
  }
}
```

```js
<ErrorBoundary>
  <MyWidget />
</ErrorBoundary>
```

无法捕捉的异常：

- 异步代码（例如 setTimeout 或 requestAnimationFrame 回调函数）
- 服务端渲染
- 它自身抛出来的错误（并非它的子组件）

> 注意错误边界仅可以捕获其子组件的错误，它无法捕获其自身的错误。如果一个错误边界无法渲染错误信息，则错误会冒泡至最近的上层错误边界，这也类似于 JavaScript 中 catch {} 的工作机制。

## vue errorHandler

- [app.config.errorHandler](https://cn.vuejs.org/api/application.html#app-config-errorhandler)

```ts
interface AppConfig {
  errorHandler?: (
    err: unknown,
    instance: ComponentPublicInstance | null,
    // `info` 是一个 Vue 特定的错误信息
    // 例如：错误是在哪个生命周期的钩子上抛出的
    info: string,
  ) => void
}
```

```js
app.config.errorHandler = (err, instance, info) => {
  // 处理错误，例如：报告给一个服务
}
```

## 原生异常捕获

> react / vue 为我们提供的 api 只能捕获框架内部的一些异常，但是对于应用开发来说，还存在资源加载异常（如图片、cdn 引用的资源），框架外的 js 异常，所以还额外的异常捕获

### 代码异常捕获

```js
// ............正常异常捕获..............
try {
  // doSomething
} catch(err) {
  // catch err
}

// ............promise异常捕获..............
promise.resolve().then(res=> {
  // doSomething
}).catch(err) {
  // doSomething
}

// ............async-await 异常捕获..............
async func() {
  try {
    const res = await Fetch('https://xxxxxxxxxx')
  } catch(err) {
    // doSomething
  }
}

// ............promise 优化异常捕获..............
const to = (promise) => {
  return promise().then(res => [null, res]).catch(err => [err, null])
}

async func() {
  const [err, res] = await to(Fetch('http://xxxxxxxxxxxx'))
}
```

### 图片加载异常捕获

```js
const image = new Image()
image.onload = (url) => {
  // doSomething
}

image.onerror = (err) => {
  // doSomething
}
```

### 统一异常捕获

```js
window.onerror = (err) => {
  // doSomething
}
```